### ISSUE TITLE
Not working on correct passwords

### ISSUE THREAD

**Issue by 0verd0se** [Sanix-Darker/Brute-Force-Login#7]
i tried this on a website, even though the username and password were correct. The script said it's incorrect.

**Comment by Kali95739** [comment]
How did you even get this tool to work?😂Everytime I try it it makes the username test and a automatic password list?

**Comment by Sanix-Darker** [comment]
@0verd0se How did you perform the test, can you share your test case ? and some logs with more details ?

**Comment by Sanix-Darker** [comment]
@Kali95739 That's how it was made, before using a tool make sure to understand how it's works, you can not eat soup with a knife !
How did you test and what did you get ? So that i can help !

**Comment by Kali95739** [comment]
I'm trying to understand but no one has an tutorial for this tool anywhere 😢 I'm using python3 and manual mode because automatic isn't ready yet and when I enter the url and username parameter and password parameter it instantly connects with the username test and automatic password list how to make it give me an option to set the username and password list because it's not right now?

**Comment by Sanix-Darker** [comment]
You just have to edit `./ressources/users.txt` and `./ressources/passwords.txt` to insert/set Your credentials, you want to test !
